
stages:
    - test
    - build
    - deploy

run_tests:
    stage: test
    image: python:3.6.8
    before_script:
        - pip install --upgrade pip
        - pip install -r requirements.txt
    script:
        - python -m pytest

