---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catapp
  template:
    metadata:
      labels:
        app: catapp
    spec:
      containers:
      - name: catapp
        image: bhimanshu/cat:beta1
        env:
        - name: SQLALCHEMY_DATABASE_URI
          value: "mysql+pymysql://root:Jnpr123!@10.85.216.114:3306/cat"
        - name: SQLALCHEMY_BINDS
          value: '{"provision": "mysql+pymysql://root:Jnpr123!@10.85.216.114:3306/provision"}'
        - name: BEARER_TOKEN
          value: "XXXXX"
        - name: ENVIRONMENT
          value: "PRODUCTION"
        ports:
        - containerPort: 80
          name: nginx
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: nginx
          initialDelaySeconds: 120
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: catapp-service
spec:
  type: NodePort
  selector:
    app: catapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
    name: nginx
