"""removed unique case constraint on SalesForceCases table

Revision ID: 0e867d21ba8e
Revises: 13f95c27467d
Create Date: 2024-01-31 17:20:03.620937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e867d21ba8e'
down_revision = '13f95c27467d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salesforce_cases', schema=None) as batch_op:
        batch_op.drop_index('case_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salesforce_cases', schema=None) as batch_op:
        batch_op.create_index('case_id', ['case_id'], unique=False)

    # ### end Alembic commands ###
