"""added case assignment history to cases table

Revision ID: 13f95c27467d
Revises: 61c9ec327030
Create Date: 2024-01-27 18:47:20.682851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13f95c27467d'
down_revision = '61c9ec327030'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assignment_history', sa.String(length=2000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_column('assignment_history')

    # ### end Alembic commands ###
