"""added account_name for case

Revision ID: 21836f2a8564
Revises: cf27b80adb07
Create Date: 2024-01-09 02:08:05.012196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21836f2a8564'
down_revision = 'cf27b80adb07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sf_account_name', sa.String(length=2000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_column('sf_account_name')

    # ### end Alembic commands ###
