"""added table SalesforceApiRequests

Revision ID: 5331afe5b47c
Revises: 21836f2a8564
Create Date: 2024-01-09 02:15:04.549629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5331afe5b47c'
down_revision = '21836f2a8564'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salesforce_api_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('response', sa.String(length=1000), nullable=True),
    sa.Column('details', sa.String(length=1000), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('salesforce_api_requests')
    # ### end Alembic commands ###
