"""added sf_init_email_name column to products

Revision ID: 61c9ec327030
Revises: c905a1f09e7a
Create Date: 2024-01-16 16:37:51.516666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61c9ec327030'
down_revision = 'c905a1f09e7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sf_init_email_name', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('sf_init_email_name')

    # ### end Alembic commands ###
