"""Increased email subject column size

Revision ID: a8309e859ee2
Revises: 
Create Date: 2023-12-30 18:17:51.678045

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a8309e859ee2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salesforce_emails', schema=None) as batch_op:
        batch_op.alter_column('email_subject',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salesforce_emails', schema=None) as batch_op:
        batch_op.alter_column('email_subject',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###
