"""added case monitoring column to user

Revision ID: b0e613d90513
Revises: e3cd27af05f0
Create Date: 2024-01-03 23:06:53.125275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0e613d90513'
down_revision = 'e3cd27af05f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monitor_case_updates', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('monitor_case_updates')

    # ### end Alembic commands ###
