"""sf_enabled column added

Revision ID: c905a1f09e7a
Revises: 5331afe5b47c
Create Date: 2024-01-10 17:56:45.971249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c905a1f09e7a'
down_revision = '5331afe5b47c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sf_enabled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('sf_enabled')

    # ### end Alembic commands ###
