"""add product series and platform column names product

Revision ID: cf27b80adb07
Revises: b0e613d90513
Create Date: 2024-01-08 22:47:35.596243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf27b80adb07'
down_revision = 'b0e613d90513'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sf_product_series', sa.String(length=2000), nullable=True))
        batch_op.add_column(sa.Column('sf_platform', sa.String(length=2000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('sf_platform')
        batch_op.drop_column('sf_product_series')

    # ### end Alembic commands ###
