"""remove constraint on email name

Revision ID: f47c8b2b47fc
Revises: a8309e859ee2
Create Date: 2023-12-30 18:22:03.681166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f47c8b2b47fc'
down_revision = 'a8309e859ee2'
branch_labels = None
depends_on = None


def upgrade():
    # pass
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salesforce_emails', schema=None) as batch_op:
        batch_op.drop_constraint('salesforce_emails_ibfk_2', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salesforce_emails', schema=None) as batch_op:
        batch_op.create_foreign_key('salesforce_emails_ibfk_2', 'product', ['email_name'], ['productname'])

    # ### end Alembic commands ###
