"""added sf_mist_product column to product

Revision ID: faf5ac5c1675
Revises: 0e867d21ba8e
Create Date: 2024-08-16 16:30:46.836528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faf5ac5c1675'
down_revision = '0e867d21ba8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sf_mist_product', sa.String(length=2000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('sf_mist_product')

    # ### end Alembic commands ###
